---
# title: role-samba4-replica-ad-dc
# Author: Rafael R. M.
# Version: 1.0
# File: tasks/ubuntu-2204-amd64-repl.yml
#
# Description: Joining a replica Active Directory Domain Controller on Ubuntu 22.04
#              with TLS/LDAP hardening and a validation flag to ensure idempotency.

- name: "Setup before creating a primary Active Directory Domain Controller on Ubuntu 22.04"
  import_tasks: ubuntu-2204-amd64-pre.yml

- name: "Join domain as replica DC"
  raw: >
    samba-tool domain join
    {{ smb_realm }}
    DC
    -U "{{ smb_username }}%{{ smb_password }}"
    --dns-backend=SAMBA_INTERNAL
    --option="idmap_ldb:use rfc2307 = yes"
  when:
    - smb_dc_result.rc != 0
  notify: restart_samba_ad_dc

- name: "Setup after creating a primary Active Directory Domain Controller on Ubuntu 22.04"
  import_tasks: ubuntu-2204-amd64-post.yml