---
# title: role-samba4-primary-ad-dc
# Author: Rafael R. M.
# Version: 1.0
# File: tasks/ubuntu-2204-amd64.yml
#
# Description: Creating a primary Active Directory Domain Controller on Ubuntu 22.04
#              with TLS/LDAP hardening and a validation flag to ensure idempotency.

- name: "Setup before creating a primary Active Directory Domain Controller on Ubuntu 22.04"
  import_tasks: ubuntu-2204-amd64-pre.yml

- name: "Provision domain"
  raw: >
    samba-tool domain provision
    --server-role=dc
    --use-rfc2307
    --dns-backend=SAMBA_INTERNAL
    --realm={{ smb_realm }}
    --domain={{ smb_workgroup }}
    --adminpass={{ smb_password }}
  when:
    - smb_dc_result.rc != 0

- name: "Transfer resolv.conf.j2 to /etc/resolv.conf"
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf

- name: "Setup after creating a primary Active Directory Domain Controller on Ubuntu 22.04"
  import_tasks: ubuntu-2204-amd64-post.yml