---
# title: role-samba4-primary-ad-dc
#
# Author: bitfinity-nl
# Version: 1.0
# File: handlers/main.yml
#
# Description: Creating a primary Active Directory Domain Controller.

- name: "restart_samba"
  ansible.builtin.systemd_service:
    state: restarted
    name: samba-ad-dc.service

- name: restart_ssh
  ansible.builtin.systemd_service:
    name: ssh
    state: restarted

- name: restart_sssd
  ansible.builtin.systemd_service:
    name: sssd
    state: restarted