---
# title: role-samba4-primary-ad-dc
#
# Author: bitfinity-nl
# Version: 1.0
# File: handlers/main.yml
#
# Description: Creating a primary Active Directory Domain Controller.

- name: "restart_samba_ad_dc"
  ansible.builtin.systemd_service:
    state: restarted
    name: samba-ad-dc.service

- name: "restart_smbd"
  ansible.builtin.systemd_service:
    state: restarted
    name: smbd.service

- name: "restart_winbind"
  ansible.builtin.systemd_service:
    state: restarted
    name: winbind.service

- name: "restart_nmbd"
  ansible.builtin.systemd_service:
    state: restarted
    name: nmbd.service

- name: restart_ssh
  ansible.builtin.systemd_service:
    name: ssh
    state: restarted

- name: restart_sssd
  ansible.builtin.systemd_service:
    name: sssd
    state: restarted

- name: restart_nscd
  ansible.builtin.systemd:
    name: nscd
    state: restarted
  # Ensure NSCD is installed and running
  when: ansible_facts.services['nscd'] is defined

- name: restart_ntp
  ansible.builtin.systemd_service:
    name: ntp
    state: restarted
  # Ensure NTP is installed and running
  when: ansible_facts.services['ntp'] is defined